### PR TITLE
thanks to BM

### PR DESCRIPTION
**Pull request by Havrysh**

### CODE REVIEW

**Review by alexandra-protyanova — CHANGES_REQUESTED** [review]
add demo link to your PR

**Review by valerii-derkach — CHANGES_REQUESTED** [review]
please provide the correct demo link and add it to the description
https://www.loom.com/share/fc505f0cc0594de2bbbf38cb8896fd4c

**Comment by Havrysh** [comment]
https://havrysh.github.io/react_goods-selector/

**Review by ArturErmolenko — APPROVED** [review]
Well done 👍

**Pull request closed without merging**
